services:
  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file:
      - .env
volumes:
  pg: